# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304ea6ba9ead549413566d967d42286037e238f549c1865b15b191e54c36c8b6cbee6b574bb3eae2eac6b264bbb850ce55910ff7502892669a0a1ee6e596f8cf

test:
  secret_key_base: 16a64befff690fef6e023025609123d9abfa819e980a8c2a338e9291894c6506b6c918da7ce083ecbd5aecf5f3e57d732bcc6e0a9efac0920e44f8a1d7fb5ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
